version: '3'

services:

  laravel:
    build:
      context: ./laravel
      dockerfile: Dockerfile.prod
    image: fc_laravel:prod
    container_name: fc_laravel
    networks:
      - laranet
  
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: fc_nginx:prod
    container_name: fc_nginx 
    networks:
      - laranet
    ports:
      - "8080:80"

networks:
  laranet:
    driver: bridge